title: "cat-edit-mml"
description: "cat-edit-mml"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/cat-edit-mml
plugins:
  - jekyll-sitemap
